WIP
lesalonapp/kalamata pull request #2
Opened 2019-07-03 14:33 UTC by marine6

2019-07-06 13:51 UTC, nabilfreeman commented on src/index.js
> +        app.get(options.apiRoot + opts.endpointName, async function(req, res, next) {
async/await will break versions of Node.js older than v7 which is still widely used on a lot of servers.

Ideally we use vanilla promises here instead.

2019-07-06 13:55 UTC, nabilfreeman requested changes
Please make a few improvements to the code quality 😁

2019-07-06 13:55 UTC, nabilfreeman commented on src/index.js
> +                const { total_items, total_pages } = await mod.count('id').then(total_items => ({total_items, total_pages: Math.ceil(total_items/page_size_number)}))
Can we split this objects onto newlines so it's easier to browse and read by other contributors?

```
mod.count('id').then(total_items => ({
    total_items,
    total_pages: Math.ceil(total_items / page_size_number)
}))
```

2019-07-06 13:55 UTC, nabilfreeman commented on src/index.js
> +                    res.header('x-prev', `${req.route.path}?page=${page_number - 1}&page_size=${page_size_number}&load=${req.query.load ? req.query.load: ''}`);
I think the same down here, especially with the long template strings, separate lines would be a lot better.

2019-07-06 13:55 UTC, nabilfreeman commented on src/index.js
> +                    const left_items = total_items - (page_number-1)*page_size_number;
Lots of inconsistent spacing like around the * on this line

2019-07-08 15:49 UTC, MarieFindlay approved these changes

2019-07-09 10:11 UTC, merged